# coding=utf-8
"""HTML报告生成模块"""

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from src.crawler.data_processor import format_date_folder, get_output_path
from src.utils.logger import logger


class HTMLReportGenerator:
    """HTML报告生成器"""

    def __init__(self):
        self.template = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TrendRadar - 活动创意灵感报告</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; padding: 20px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 12px; margin-bottom: 20px; }
        .header h1 { font-size: 24px; margin-bottom: 5px; }
        .header p { opacity: 0.9; font-size: 14px; }
        .news-card { background: white; border-radius: 8px; padding: 20px; margin-bottom: 16px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        .news-title { font-size: 18px; font-weight: 600; color: #1a1a1a; margin-bottom: 12px; }
        .news-meta { font-size: 12px; color: #999; margin-bottom: 12px; }
        .news-content { font-size: 14px; line-height: 1.8; color: #333; }
        .highlight { background: #fff3cd; padding: 8px 12px; border-radius: 4px; margin: 8px 0; }
        .tag { display: inline-block; padding: 4px 10px; background: #e8f4fd; color: #1e88e5; border-radius: 12px; font-size: 12px; margin-right: 6px; }
        .source-link { color: #1e88e5; text-decoration: none; font-size: 13px; }
        .footer { text-align: center; padding: 20px; color: #999; font-size: 12px; }
        .stats-bar { display: flex; gap: 20px; margin-bottom: 20px; }
        .stat-item { background: white; padding: 16px 24px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        .stat-value { font-size: 28px; font-weight: 700; color: #667eea; }
        .stat-label { font-size: 12px; color: #999; margin-top: 4px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 今日活动创意灵感报告</h1>
            <p>更新时间：{update_time}</p>
        </div>
        
        <div class="stats-bar">
            <div class="stat-item">
                <div class="stat-value">{total_count}</div>
                <div class="stat-label">匹配新闻</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">{platform_count}</div>
                <div class="stat-label">监控平台</div>
            </div>
        </div>
        
        {news_items}
        
        <div class="footer">
            <p>Generated by TrendRadar | 热点趋势雷达</p>
        </div>
    </div>
</body>
</html>
        """

    def generate(self, report_data: Dict) -> str:
        """生成HTML报告"""
        update_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        total_count = 0
        platform_count = 0
        
        for stat in report_data.get("stats", []):
            total_count += len(stat.get("titles", []))
            platform_count += 1
        
        news_items = []
        for stat in report_data.get("stats", []):
            for title_data in stat.get("titles", []):
                title = title_data.get("title", "")
                url = title_data.get("url", "")
                source = title_data.get("source", "")
                
                item_html = f"""
        <div class="news-card">
            <div class="news-title">📌 {title}</div>
            <div class="news-meta">来源: {source}</div>
            <div class="news-content">
                <div class="highlight">✨ 核心创意：待分析</div>
                <div class="highlight">🔧 可复用元素：待分析</div>
            </div>
            {f'<a href="{url}" class="source-link" target="_blank">🔗 查看原文</a>' if url else ''}
        </div>
                """
                news_items.append(item_html)
        
        html = self.template.format(
            update_time=update_time,
            total_count=total_count,
            platform_count=platform_count,
            news_items="\n".join(news_items)
        )
        
        return html

    def save(self, report_data: Dict) -> str:
        """保存HTML报告到文件"""
        html_content = self.generate(report_data)
        filename = f"{datetime.now().strftime('%H时%M分')}.html"
        file_path = get_output_path("html", filename)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        
        logger.info(f"HTML报告已保存到: {file_path}")
        return file_path